language: elixir
sudo: false

branches:
  only:
    - master
    - development

elixir:
  - 1.8.1
otp_release:
  - 21.0
  - 21.1
  - 21.2
  - 21.3

matrix:
  include:
    - elixir: 1.4.0
      otp_release: 19.1
    - elixir: 1.4.4
      otp_release: 19.1
    - elixir: 1.5.0
      otp_release: 19.1
    - elixir: 1.5.3
      otp_release: 20.2
    - elixir: 1.6.0
      otp_release: 20.2
    - elixir: 1.6.6
      otp_release: 20.3
    - elixir: 1.6.6
      otp_release: 21.3
    - elixir: 1.7.0
      otp_release: 20.3
    - elixir: 1.7.3
      otp_release: 20.3
    - elixir: 1.8.2
      otp_release: 21.2.4
    - elixir: 1.9.0
      otp_release: 22.0
