language: elixir
sudo: false

branches:
  only:
    - master
    - development

elixir:
  - 1.6.6
  - 1.7.2
otp_release:
  - 20.0
  - 20.1
  - 20.2
  - 20.3

matrix:
  include:
    - elixir: 1.4.0
      otp_release: 19.1
    - elixir: 1.4.4
      otp_release: 19.1
    - elixir: 1.4.4
      otp_release: 19.2
    - elixir: 1.5.3
      otp_release: 20.2
    - elixir: 1.5.0
      otp_release: 19.1
    - elixir: 1.5.1
      otp_release: 20.2
    - elixir: 1.5.2
      otp_release: 20.2
    - elixir: 1.5.3
      otp_release: 20.2
    - elixir: 1.6.0
      otp_release: 20.2
    - elixir: 1.6.4
      otp_release: 20.2
    - elixir: 1.6.5
      otp_release: 21.0
    - elixir: 1.7.0
      otp_release: 21.0
    - elixir: 1.7.1
      otp_release: 21.0
