# language: elixir
# sudo: false
# elixir:
#   - 1.0.5
#   - 1.1
# otp_release:
#   - 17.5
#   - 18.0
language: elixir
sudo: false

branches:
  only:
    - master
    - development

elixir:
  - 1.0.5
  - 1.1
otp_release: 
  - 17.5
  - 18.0

matrix:
  include:
    - elixir: 1.2.0
      otp_release: 18.0 
