language: elixir
sudo: false

branches:
  only:
    - master
    - development

elixir:
  - 1.9.0
  - 1.9.2
otp_release:
  - 21.0
  - 22.0
  - 22.0.7

matrix:
  include:
    - elixir: 1.7.0
      otp_release: 20.3
    - elixir: 1.7.3
      otp_release: 20.3
    - elixir: 1.8.2
      otp_release: 21.2.4
    - elixir: 1.9.0
      otp_release: 21.1
    - elixir: 1.9.1
      otp_release: 21.3
